### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by hamuchan214** [ShitaLab-TMCIT/ShitaLab#37]
![image](https://github.com/user-attachments/assets/e4964c42-96c8-484e-b058-b56973a2e617)
リポジトリの説明文が
IEEE80.211になってる

**Comment by ryoww** [comment]
俺これGitHubのAPIからとってきてるからタイポしてるとしたらIEEEリポジトリのどこかのdescriptionがタイポしてる

**Comment by hamuchan214** [comment]
ごめんこっちが間違ってたわ
修正したのでクローズ
